version: '3.5'

services:

  backend:
      build: ./backend-example-docker
      environment:
        - REDIS=redis
        - REDIS_PORT=6379
      ports: 
        - 8000:8000
      depends_on:
        - redis
      restart: 
        unless-stopped

  redis:
      image: redis
      hostname: redis
      restart: 
        unless-stopped
      ports: 
        - 6379


  frontend:
      build: ./frontend-example-docker
      environment:
        - NODE_ENV='production'
      ports: 
        - 5000:5000